# Generated by Django 6.0.4 on 2026-08-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "payment",
            "0004_rename_date_order_date_ordered_order_date_delivered_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={"verbose_name_plural": "Shipping Addresses"},
        ),
    ]
