# Generated by Django 6.0.4 on 2026-05-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_remove_order_product_remove_order_quantity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "catagories"},
        ),
        migrations.AddField(
            model_name="product",
            name="on_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
