# Generated by Django 6.0.4 on 2026-05-07 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_category_options_product_on_sale_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="artist_name",
        ),
        migrations.AddField(
            model_name="product",
            name="track_list",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="vinyl_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendor",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendor",
            name="phone_number",
            field=models.CharField(default="Not Provided", max_length=20),
            preserve_default=False,
        ),
    ]
