# Generated by Django 6.0.4 on 2026-05-27 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_category_options_category_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "catagories"},
        ),
    ]
