# Generated by Django 6.0.4 on 2026-05-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_category_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="address",
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="address1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="address2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="country",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="province",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="zipcode",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
