# Generated by Django 6.0.4 on 2026-05-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_remove_customerprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/vendor/"),
        ),
    ]
