# Generated by Django 6.0.4 on 2026-05-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_vendor_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="old_cart",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
