# Generated by Django 6.0.4 on 2026-06-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_customerprofile_old_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
