# Generated by Django 6.0.4 on 2026-07-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="product",
            name="ratings_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vendor",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="vendor",
            name="ratings_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
