# Generated by Django 6.0.4 on 2026-07-22 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_product_average_rating_product_ratings_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
