# Generated by Django 6.0.4 on 2026-07-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_vendor_added_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ratings",
            options={"verbose_name_plural": "ratings"},
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/category/"
            ),
        ),
    ]
