# Generated by Django 6.0.4 on 2026-08-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_alter_ratings_options_category_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
    ]
