from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about_us, name='aboutus'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('become_vendor/', views.become_vendor, name='become_vendor'),
    path('update_user/', views.update_user, name='update_user'),
    path('update_info/', views.update_info, name='update_info'),
    path('update_password/', views.update_password, name='update_password'),
    path('vendor/', views.vendor_dashboard, name='vendor'),
    path('add_product/', views.add_product, name='add_product'),
    path('productdetail/<int:pk>', views.product_detail, name='productdetail'),
    path('store_detail/<int:pk>', views.store_detail, name='store_detail'),
    path('category/<str:slug>', views.category, name='category'),
    path('genre_summary/', views.genre_summary, name='genre_summary'),
    path('record_collection_summary/', views.record_collection_summary, name='record_collection_summary'),
    path('record_store_summary/', views.record_store_summary, name='record_store_summary'),
    path('search/', views.search, name='search'),
    path('vendor_dashboard', views.vendor_dashboard, name='vendor_dashboard'),
    path('popular_store/', views.popular_store, name='popular_store'),
    path('new_store/', views.new_store, name='new_store'),
    path('popular_vinyls/', views.popular_vinyls, name='popular_vinyls'),
    path('fresh_arrivals/', views.fresh_arrivals, name='fresh_arrivals'),
    path('new_store/', views.new_store, name='new_store'),
    path('rate_product/<int:product_id>/rate', views.rate_product, name='rate_product'),
    path('rate_product/<int:vendor_id>/rate', views.rate_vendor, name='rate_vendor'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset',),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_sent.html'), name='password_reset_done',),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_form.html'), name='password_reset_confirm',),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_complete',),
]